// gameModeMapping.js

const gameModeMapping = {
  0: "Unknown",
  1: "All Pick",
  2: "Captains Mode",
  3: "Random Draft",
  4: "Single Draft",
  5: "All Random",
  6: "Intro",
  7: "Diretide",
  8: "Reverse Captains Mode",
  9: "Greeviling",
  10: "Tutorial",
  11: "Mid Only",
  12: "Least Played",
  13: "Limited Heroes",
  14: "Compendium Matchmaking",
  15: "Custom",
  16: "Captains Draft",
  17: "Balanced Draft",
  18: "Ability Draft",
  19: "Event",
  20: "All Random Death Match",
  21: "1v1 Mid",
  22: "All Pick",
  23: "Turbo",
  24: "Mutation",
  25: "Co-op vs. Bots",
  26: "Ranked All Pick",
  27: "Aghanim's Labyrinth",
  28: "Reverse Captains Draft",
  29: "Overthrow",
  30: "Halloween",
  31: "Diretide",
  32: "Frostivus",
  33: "The Greeviling",
  34: "Tutorial",
  35: "Mid Only",
  36: "Least Played",
  37: "New Player Pool",
  38: "Compendium Matchmaking",
  39: "Custom",
  40: "Captains Draft",
  41: "Balanced Draft",
  42: "Ability Draft",
  43: "Event",
  44: "All Random Death Match",
  45: "1v1 Mid",
  46: "All Draft",
  47: "Turbo",
  48: "Mutation",
  49: "Co-op vs. Bots",
  50: "Overthrow",
  51: "Snowball",
  52: "Year Beast",
  53: "Year Beast Brawl",
  54: "1v1 Mid",
  55: "All Random Death Match",
  56: "Solo Mid",
  57: "Mid Only",
  58: "All Draft",
  59: "Turbo",
  60: "Mutation",
  61: "Battle Royale",
  62: "Gambit",
  63: "1v1 Mid Solo",
  64: "All Random",
  65: "Turbo",
  66: "Mid Only",
  67: "Least Played",
  68: "Limited Heroes",
  69: "Compendium Matchmaking",
  70: "Custom",
  71: "Captains Draft",
  72: "Balanced Draft",
  73: "Ability Draft",
  74: "Event",
  75: "All Random Death Match",
  76: "1v1 Mid",
  77: "Captains Mode",
  78: "Turbo",
  79: "Mutation",
  80: "Co-op vs. Bots",
  81: "Solo Mid 1v1",
  82: "Ranked All Pick",
  83: "Mid Only",
  84: "All Pick",
  85: "Turbo",
  86: "Mutation",
  87: "Co-op vs. Bots",
  88: "Overthrow",
  89: "Snowball",
  90: "Event",
  91: "Greeviling",
  92: "Diretide",
  93: "Winter Battle Pass",
  94: "Tutorial",
  95: "1v1 Mid",
  96: "Battle Cup",
  97: "Ranked Roles",
  // Add more game modes as needed
};

module.exports = gameModeMapping;
