// heroMapping.js

export const heroNamesMapping = {
  1: "Anti-Mage",
  2: "Axe",
  3: "Bane",
  4: "Bloodseeker",
  5: "Crystal Maiden",
  6: "Drow Ranger",
  7: "Earthshaker",
  8: "Juggernaut",
  9: "Mirana",
  10: "Morphling",
  11: "Shadow Fiend",
  12: "Phantom Lancer",
  13: "Puck",
  14: "Pudge",
  15: "Razor",
  16: "Sand King",
  17: "Storm Spirit",
  18: "Sven",
  19: "Tiny",
  20: "Vengeful Spirit",
  21: "Windranger",
  22: "Zeus",
  23: "Kunkka",
  25: "Lina",
  26: "Lion",
  27: "Shadow Shaman",
  28: "Slardar",
  29: "Tidehunter",
  30: "Witch Doctor",
  31: "Lich",
  32: "Riki",
  33: "Enigma",
  34: "Tinker",
  35: "Sniper",
  36: "Necrophos",
  37: "Warlock",
  38: "Beastmaster",
  39: "Queen of Pain",
  40: "Venomancer",
  41: "Faceless Void",
  42: "Wraith King",
  43: "Death Prophet",
  44: "Phantom Assassin",
  45: "Pugna",
  46: "Templar Assassin",
  47: "Viper",
  48: "Luna",
  49: "Dragon Knight",
  50: "Dazzle",
  51: "Clockwerk",
  52: "Leshrac",
  53: "Nature's Prophet",
  54: "Lifestealer",
  55: "Dark Seer",
  56: "Clinkz",
  57: "Omniknight",
  58: "Enchantress",
  59: "Huskar",
  60: "Night Stalker",
  61: "Broodmother",
  62: "Bounty Hunter",
  63: "Weaver",
  64: "Jakiro",
  65: "Batrider",
  66: "Chen",
  67: "Spectre",
  68: "Ancient Apparition",
  69: "Doom",
  70: "Ursa",
  71: "Spirit Breaker",
  72: "Gyrocopter",
  73: "Alchemist",
  74: "Invoker",
  75: "Silencer",
  76: "Outworld Destroyer",
  77: "Lycan",
  78: "Brewmaster",
  79: "Shadow Demon",
  80: "Lone Druid",
  81: "Chaos Knight",
  82: "Meepo",
  83: "Treant Protector",
  84: "Ogre Magi",
  85: "Undying",
  86: "Rubick",
  87: "Disruptor",
  88: "Nyx Assassin",
  89: "Naga Siren",
  90: "Keeper of the Light",
  91: "Io",
  92: "Visage",
  93: "Slark",
  94: "Medusa",
  95: "Troll Warlord",
  96: "Centaur Warrunner",
  97: "Magnus",
  98: "Timbersaw",
  99: "Bristleback",
  100: "Tusk",
  101: "Skywrath Mage",
  102: "Abaddon",
  103: "Elder Titan",
  104: "Legion Commander",
  105: "Techies",
  106: "Ember Spirit",
  107: "Earth Spirit",
  108: "Underlord",
  109: "Terrorblade",
  110: "Phoenix",
  111: "Oracle",
  112: "Winter Wyvern",
  113: "Arc Warden",
  114: "Monkey King",
  119: "Dark Willow",
  120: "Pangolier",
  121: "Grimstroke",
  126: "Void Spirit",
  128: "Snapfire",
  129: "Mars"
};

export const heroImagesMapping = {
  1: 'hero-antimage',
  2: 'hero-axe',
  3: 'hero-bane',
  4: 'hero-bloodseeker',
  5: 'hero-crystal-maiden',
  6: 'hero-drow-ranger',
  7: 'hero-earthshaker',
  8: 'hero-juggernaut',
  9: 'hero-mirana',
  10: 'hero-morphling',
  11: 'hero-shadow-fiend',
  12: 'hero-phantom-lancer',
  13: 'hero-puck',
  14: 'hero-pudge',
  15: 'hero-razor',
  16: 'hero-sand-king',
  17: 'hero-storm-spirit',
  18: 'hero-sven',
  19: 'hero-tiny',
  20: 'hero-vengeful-spirit',
  21: 'hero-windranger',
  22: 'hero-zeus',
  23: 'hero-kunkka',
  25: 'hero-lina',
  26: 'hero-lion',
  27: 'hero-shadow-shaman',
  28: 'hero-slardar',
  29: 'hero-tidehunter',
  30: 'hero-witch-doctor',
  31: 'hero-lich',
  32: 'hero-riki',
  33: 'hero-enigma',
  34: 'hero-tinker',
  35: 'hero-sniper',
  36: 'hero-necrophos',
  37: 'hero-warlock',
  38: 'hero-beastmaster',
  39: 'hero-queen-of-pain',
  40: 'hero-venomancer',
  41: 'hero-faceless-void',
  42: 'hero-wraith-king',
  43: 'hero-death-prophet',
  44: 'hero-phantom-assassin',
  45: 'hero-pugna',
  46: 'hero-templar-assassin',
  47: 'hero-viper',
  48: 'hero-luna',
  49: 'hero-dragon-knight',
  50: 'hero-dazzle',
  51: 'hero-clockwerk',
  52: 'hero-leshrac',
  53: 'hero-natures-prophet',
  54: 'hero-lifestealer',
  55: 'hero-dark-seer',
  56: 'hero-clinkz',
  57: 'hero-omniknight',
  58: 'hero-enchantress',
  59: 'hero-huskar',
  60: 'hero-night-stalker',
  61: 'hero-broodmother',
  62: 'hero-bounty-hunter',
  63: 'hero-weaver',
  64: 'hero-jakiro',
  65: 'hero-batrider',
  66: 'hero-chen',
  67: 'hero-spectre',
  68: 'hero-ancient-apparition',
  69: 'hero-doom',
  70: 'hero-ursa',
  71: 'hero-spirit-breaker',
  72: 'hero-gyrocopter',
  73: 'hero-alchemist',
  74: 'hero-invoker',
  75: 'hero-silencer',
  76: 'hero-outworld-destroyer',
  77: 'hero-lycan',
  78: 'hero-brewmaster',
  79: 'hero-shadow-demon',
  80: 'hero-lone-druid',
  81: 'hero-chaos-knight',
  82: 'hero-meepo',
  83: 'hero-treant-protector',
  84: 'hero-ogre-magi',
  85: 'hero-undying',
  86: 'hero-rubick',
  87: 'hero-disruptor',
  88: 'hero-nyx-assassin',
  89: 'hero-naga-siren',
  90: 'hero-keeper-of-the-light',
  91: 'hero-io',
  92: 'hero-visage',
  93: 'hero-slark',
  94: 'hero-medusa',
  95: 'hero-troll-warlord',
  96: 'hero-centaur-warrunner',
  97: 'hero-magnus',
  98: 'hero-timbersaw',
  99: 'hero-bristleback',
  100: 'hero-tusk',
  101: 'hero-skywrath-mage',
  102: 'hero-abaddon',
  103: 'hero-elder-titan',
  104: 'hero-legion-commander',
  105: 'hero-techies',
  106: 'hero-ember-spirit',
  107: 'hero-earth-spirit',
  108: 'hero-underlord',
  109: 'hero-terrorblade',
  110: 'hero-phoenix',
  111: 'hero-oracle',
  112: 'hero-winter-wyvern',
  113: 'hero-arc-warden',
  114: 'hero-monkey-king',
  119: 'hero-dark-willow',
  120: 'hero-pangolier',
  121: 'hero-grimstroke',
  126: 'hero-void-spirit',
  128: 'hero-snapfire',
  129: 'hero-mars'
};
